name: execute-discourse-query
description: Executes a Discourse data-explorer query via the API
inputs:
  discourseKey:
    description: The "all users" API key for your Discourse instance
    required: true
  format:
    description: "The format to store the results in: either 'json' or 'markdown'"
    default: json
  hostname:
    description: Hostname of your Discourse instance
    required: true
  id:
    description: ID of the query to execute
    required: true
  params:
    description: JSON object containing the parameters for the query
  path:
    description: File path to store the results in
    required: true
outputs:
  path:
    description: File path where the results were stored
runs:
  using: node12
  main: dist/index.js
